---
- name: Check dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  become: yes
- name: Add Docker Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes
- name: Get Ubuntu release name
  shell: lsb_release -cs
  register: release_name
- name: Add Docker Repositories
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ release_name.stdout }} {{ item }}"
    state: present
    update_cache: no
  with_items:
    - stable
    - edge
  become: yes
- name: Install Docker
  apt:
    name: "docker-ce={{ docker_version }}"
    state: present
    update_cache: yes
  become: yes
